# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3a04a84fdbdf8f6c1c0ac35679c97ebc9cf02d7150df43685b163c4b08da2825f1541d265b192082ee39a4de397169d506521da9727cdfbec5693888c47a1e6

test:
  secret_key_base: 01ed231e835d137a719baa1e8b9b6a89e9cd0466ee2bfe16b192db67116626792eb127642d6d1d299276857404441d85111dd1bf4a98134d92cd476bcec6f111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
